version: "3.9"

services:
  backend:
    build: ./backend
    container_name: peliculas-backend
    restart: always
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    networks:
      - peliculas-net

  frontend:
    build: ./frontend
    container_name: peliculas-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:4000
    depends_on:
      - backend
    networks:
      - peliculas-net

networks:
  peliculas-net:
    driver: bridge